name = "Slums MC"
author = "Josh"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea19a173fafa18e05b62b966b6e994021c848b09ad57bc0d59db2753f85438dc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
