name = "Slums MC"
author = "Josh"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6767a0fc74fa8ee1e0b1245c49088b6e08b9fb8bc17e930c7175b2fe25fa42a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
