name = "Slums MC"
author = "Josh"
version = "1.0.4-hotfix1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eba6878432910d4d9862b1d543b89ed43fa7255f60c72e1ec8c69512cc156530"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
