#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Sep 04 00:16:20 PDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=Bliss_v2.1.2_(Chocapic13_Shaders_edit).zip
